### ISSUE TITLE
GRASS 8.0.2 in PPA ubuntugis-unstable, not 8.2

### ISSUE THREAD

**Issue by mazingaro** [veroandreo/foss4g2022_grass4rs#16]
Not sure about it, so I wanted to ask in time: the [ubuntugis-unstable](https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable) doesn't offer GRASS 8.2 but 8.0.2:
was this version meant for the workshop (probably not, as 8.2 exists) and if not, how to add the 8.2 in Ubuntu?

Thanks.

**Comment by veroandreo** [comment]
As I use Fedora, I'm not aware of how things are handled in ubuntu repos. But it seems that 8.2 is still in the `experimental` PPA. See: https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-experimental

@kalxas I see you pushed grass into ubuntu-unstable, do you plan to add 8.2 as well?

**Comment by veroandreo** [comment]
@mazingaro, note that we'll also provide a notebook to run with colab

**Comment by kalxas** [comment]
Done

**Comment by mazingaro** [comment]
@veroandreo great for the Colab notebook.
@kalxas I've tested it and it works.

You are super fast, thank you!
