### ISSUE TITLE
Remaining tasks

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/foss4g2022_grass4rs#4]
- [x] edit/adapt the maxlik classifcation section of diff scenes using signatures + band ref
- [x] check section naming and numbering
- [x] add section titles to README.md for a quick overview
- [x] upload (reduced) Sentinel-2 data somewhere
- [x] add section for importing the landuse map
- [x] run everything from scratch
- [x] complete instructions in the README file and send to workshop participants
    - [x] software download
    - [x] data download
    - [x] Registration at Copernicus Open Access Hub, store username and password in two lines in a text file called `esa_credentials.txt`

**Comment by neteler** [comment]
Re: upload OSM data somewhere

What is the size? I can likely offer some space.

**Comment by veroandreo** [comment]
> Re: upload OSM data somewhere
> 
> What is the size? I can likely offer some space.

2.8 Mb :)

**Comment by neteler** [comment]
Done: https://data.neteler.org/foss4g2022/
* osm_north_carolina_landuse_epsg3358.gpkg 2.8MB
* sentinel.zip 66MB

**Comment by neteler** [comment]
Re:  add section for importing the OSM extract

This can be borrowed from here:
https://github.com/neteler/jupyter_sentinel2_grass_gis/blob/main/sentinel2_grass_gis.ipynb
--> Importing the landuse vector map

I'll take care of it in #6.

**Comment by neteler** [comment]
_Copied from https://github.com/veroandreo/foss4g2022_grass4rs/pull/10#issue-1338047862_

Pressing issues now are:
- prepare a new LULC dataset from the NC_NLCD2019 tiff to follow a similar approach to the one that we have
- prepare a folder with the desired structure and all data, we provide directly that - one link and done, participants should download in advance
- update instructions and send to participants asap
- resolution of S2 data - dunno what's wrong there really

**Comment by veroandreo** [comment]
closing as complete, reopen or create a new one if needed
