### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by petrasovaa** [veroandreo/foss4g2022_grass4rs#9]
Here is a list of things I suggest:

#### Section 4
For printing GRASS version I suggest:

    import subprocess
    print(subprocess.check_output([grassbin, "--config", "version"], text=True))

#### Section 5
For gisenv use:

    gs.gisenv()

For g.list use:

    gs.list_grouped(type="vector")

Creating new mapset - this is not completely solved API. Note that grass.grassdb package was developed for internal use only, it's not linked in the Python documentation, although it is there when you search for it. So it will likely change. You can create mapset and switch with (NOT recommended, unstable API and when you rerun the cell it will fail):

    import grass.grassdb.create as gdb
    gdb.create_mapset(grassdata, location, "sentinel2")
    session.switch_mapset("sentinel2")

Alternatives: Call grass with bash

    !grassbin -c -e ....
    session.switch_mapset(...)

Or use an existing mapset user1:

    session.switch_mapset("user1")

This is something we should address better for the next version.

#### Section 7
Avoid manual parsing:

```
import pandas as pd
from io import StringIO

pd.read_csv(StringIO(list_prod), delimiter=" ", usecols=[0, 1, 2, 4, 5, 6, 7],
            names=['uuid', 'scene', 'date', 'cloud', 'product', 'size', 'unit'])
```

Printing file content - use context manager (`with open("") as f:`) or just use `!cat ...`

#### Section 10
For getting center of region use:

    gs.region(complete=True)

#### Section 13
Instead of:

    # Set color table
    colours = ["11 195:20:0", "13 255,255,168", "14 100:240:100", "31 77:105:0", "51 0:204:242"]
    colourise = gs.feed_command("r.colors", map="sentinel_rf", rules="-", quiet=True)
    colourise.stdin.write("\n".join(colours).encode())
    colourise.stdin.close()

Use:

    gs.write_command("r.colors", map=..., rules="-", stdin="\n".join(colours))

Instead of `parse_command` with r.report, use `print(read_command(...))`, there may be more places like that.

**Comment by veroandreo** [comment]
All suggestions included, thanks :pray:
